export const GET_PRODUCT ='GET_PRODUCT';
export const CREATE_PRODUCT='CREATE_PRODUCT'
export const DELETE_PRODUCT='DELETE_PRODUCT'
export const UPDATE_PRODUCT='UPADTE_PRODUCT'
export const SINGLE_PRODUCT='SINGLE_PRODUCT'

//loader
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCHED_PRODUCT = "FETCHED_PRODUCT";